package com.akhester.smartfhir.client.launch;

import java.io.Serializable;
import java.time.Instant;
import java.util.List;

/**
 * Immutable snapshot of a SMART EHR launch — stored in the HTTP session
 * between the launch request (Task 3) and the callback (Task 5).
 *
 * <h3>What gets stored here</h3>
 * <ul>
 *   <li>{@code iss}          — FHIR base URL from Epic's launch request.
 *                              Used to look up the discovered endpoints.</li>
 *   <li>{@code launchToken}  — Opaque token from Epic ({@code ?launch=...}).
 *                              Must be sent back in the authorize request.</li>
 *   <li>{@code state}        — Random nonce generated by our app.
 *                              Validated in the callback to prevent CSRF.</li>
 *   <li>{@code authEndpoint} — Resolved from Task 2 discovery; stored here
 *                              so Task 3 can redirect without re-fetching.</li>
 *   <li>{@code tokenEndpoint}— Stored for Task 5 (token exchange).</li>
 *   <li>{@code initiatedAt}  — For session expiry checks (optional hardening).</li>
 * </ul>
 *
 * <h3>Why Serializable?</h3>
 * HttpSession serializes its attributes when sessions are distributed
 * (e.g. Spring Session + Redis). Without {@code Serializable} the session
 * would fail to replicate in clustered deployments.
 *
 * PKCE fields (code_verifier, code_challenge) live in Task 4 and are
 * added alongside this in the session by SmartLaunchController.
 */
public record SmartLaunchSession(
        String iss,
        String launchToken,
        String state,
        String authEndpoint,
        String tokenEndpoint,
        List<String> scopes,       // added Task 4 — SmartAuthRequestBuilder reads these
        Instant initiatedAt
) implements Serializable {

    // Pinned to prevent silent session invalidation during rolling deployments
    // when Redis-backed sessions are in use. Bump only on intentional schema change.
    private static final long serialVersionUID = 1L;

    /** Session attribute key — used by both Task 3 and Task 5. */
    public static final String SESSION_KEY = "smart_launch_session";

    /**
     * Factory method — sets {@code initiatedAt} to now automatically.
     * Scopes are defensively copied to guarantee immutability regardless of source.
     */
    public static SmartLaunchSession of(
            String iss,
            String launchToken,
            String state,
            String authEndpoint,
            String tokenEndpoint,
            List<String> scopes
    ) {
        return new SmartLaunchSession(iss, launchToken, state,
                authEndpoint, tokenEndpoint,
                scopes != null ? List.copyOf(scopes) : List.of(),
                Instant.now());
    }

    /**
     * Returns true if this session was initiated more than {@code maxAgeSeconds}
     * ago — used in Task 5 callback to reject stale sessions.
     */
    public boolean isOlderThan(long maxAgeSeconds) {
        return Instant.now().isAfter(initiatedAt.plusSeconds(maxAgeSeconds));
    }
}
